$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
code: ../src/training
environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04
  conda_file: ../azureml/environment.yml
command: >
  python train.py 
  --epochs 10 
  --batch_size 64 
  --output_dir outputs
compute: azureml:ci-cv01
